app:
  name: GO-subdivisions-ID
  mode: development
web:
  prefork: false
  port: 3000
log:
  level: 6
database:
  dialect: pg
  # dsn: postgresql://postgres:postgres@localhost:5432
  pool:
    idle: 6
    max: 100
    lifetime: 300